version: '3.9'

services:
  portainer:
    image: portainer/portainer
    expose:
      - "9000"
    container_name: '${APP_NAME}-docker'
    restart: always
    ports:
      - '${APP_PORT}:9000'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/data/templates:/usr/share/nginx/html"
